apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: pgadmin
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.210
  ports:
    - port: 5050
    # - protocol: TCP
    #   port: 5050
    #   targetPort: 5050
    #   nodePort: 32050
  selector:
    app: pgadmin