apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-volume
  labels:
    type: local
    app: pgadmin
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/pgadmin