apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin-ui
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pgadmin.hvo.lan`) # && PathPrefix(`/traefik`)
      kind: Rule
      # middlewares:
      #   - name: strip-traefik
      services:
        - name: pgadmin-service
          port: 80
          # port: 5050
          # kind: TraefikService
# ---
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: strip-traefik
#   namespace: default
# spec:
#   stripPrefix:
#     prefixes:
#       - "/traefik"