apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-volume-claim
  labels:
    app: pgadmin
spec:
  volumeName: pgadmin-volume
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi