apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-env
  labels:
    app: pgadmin
data:
  PGADMIN_DEFAULT_EMAIL: hvoadm@hvo.lan
  PGADMIN_DEFAULT_PASSWORD: Opus111!
  PGADMIN_CONFIG_SERVER_MODE: 'False'
  PGADMIN_LISTEN_PORT: '5050'
  PGADMIN_CONFIG_LOGIN_BANNER: '"Homelab Postgres Database"'
