apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-clusterissuer
  # namespace: cert-manager
spec:
  acme:
    email: heiko.vogeler@hvo.de
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-clusterissuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: WThrQk1jOERBQkZ3Wkljbmh5WkNYNjRpYlJMdW5KdVU0S3l3RUhhTQ==