apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-clusterissuer
  # namespace: cert-manager
spec:
  acme:
    email: heiko.vogeler@vogeler.cc
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-clusterissuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: heiko.vogeler@hvo.de
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
              # key: 7b54adb301ae3d55769dd8dceac25d6260a21
              # key: Y8kBMc8DABFwZIcnhyZCX64ibRLunJuU4KywEHaM