apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin-certificate
  # namespace: cert-manager
spec:
  # Secret names are always required.
  secretName: pgadmin-certificate-secret
  # secretName: pgadmin-vogeler-cc-tls2
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - pgadmin.vogeler.cc
