service:
  enabled: true
  type: LoadBalancer
  # annotations: {}
  # labels: {}
  spec:
    loadBalancerIP: 192.168.178.205 # this should be an IP in the Kube-VIP range
    
  # loadBalancerSourceRanges: []
  # externalIPs: []
# ports:
#   web:
#     redirectTo: 
#       port: websecure

# I do this in a separate ingress route manifest under deployments
# ingressRoute:
#   dashboard:
#     enabled: true
#     entryPoints: [web, websecure]
#     match: Host(`traefik.hvo.lan`)

dashboard:
  enabled: true
  ingressRoute:
    enabled: true
# entryPoints:
#   traefik:
#     address: ':8201'
# additionalArguments:
#   - "--api.dashboard=true"
