apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      nodeSelector:
        node-type: pi
      containers:
        - name: ubuntu-container
          image: ubuntu:latest
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          volumeMounts:
            - mountPath: /mnt/homelab
              name: smb-homelab-vol
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
      volumes:
        - name: smb-homelab-vol
          persistentVolumeClaim: 
            claimName: smb-homelab-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-homelab-claim
  namespace: default
  labels:
    node-type: pi
spec:
  volumeName: smb-homelab
  storageClassName: smb
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ki